### ISSUE TITLE
The precache-manifest Files doesn't get cleaned up

### ISSUE THREAD

**Issue by michaelsoriano** [devloco/create-react-wptheme#15]
Hi @devloco  - I'm back with more questions if you don't mind. 

I noticed that everytime I do a run wpbuild - the precache-manifest.XXXX.js files gets added - but it doesn't get rid of the old ones. Is this expected? 

Also, where's the best place to put static images? 

One last thing -  what would be the best way to have constants such as $TEMPLATE_PATH (You have it in index.php) - but I want to access it in React components? 

Thank you in advance.

**Comment by devloco** [comment]
I never noticed the manifest files, I'll look at what Facebook is doing about it, and try to follow suit. I know they are onboard with having that stuff around... I think they have something to do with Web Apps on mobile devices... I think... and if that's the case, they're a lot less interesting to WP themes. So I could probably diverge from Facebook in that case and whack them after a build.

As for static images, here's how Facebook thinks it should be done:

[Adding Images, Fonts, and Files](https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files)
[Using the Public Folder](https://facebook.github.io/create-react-app/docs/using-the-public-folder)

I would use the $TEMPLATE_PATH instead of %PUBLIC_URL% for linking to files in the public folder, if you go that route. It'll probably take some hunting to figure out exactly where everything gets copied to during a build.

To make the $TEMPLATE_PATH available to React, I would just add it as a global script at the top of index.php, like so:

`<script>
var TEMPLATE_PATH = "<?php echo $TEMPLATE_PATH; ?>";
</script>`

Then you should be able to reference `TEMPLATE_PATH` anytime in any JS/React/etc.

**Comment by devloco** [comment]
Also, this article was the inspiration for me to write `create-react-wptheme` and the author has a good section on getting PHP variables into React:

[How To Build A Skin For Your Web App With React And WordPress](https://www.smashingmagazine.com/2018/03/react-wordpress-web-app/)

Smashing Magazine doesn't seem to support linking to a particular section of their articles. So you'll have to search that page for: `A Global JavaScript Variable` to get right to that part.

**Comment by michaelsoriano** [comment]
No biggie on the precache files. Its not harming anyone - it just gets messy. Especially when checking stuff in to git.

I'm going to follow the import route for images.

Global vars - I'm going to follow your advice by adding it to index.php. I'm only going to need a few of these vars. The wp_enqueue_script route is good too - but for now, I want to keep it simple. 

Thanks again.

**Comment by devloco** [comment]
Hi @michaelsoriano,

The multiple precache files was indeed on me. It should be fixed now. Here's the obligatory link to the update instructions:

[Updating Existing Themes](https://github.com/devloco/create-react-wptheme#updating-existing-themes)

Thanks for the help with bug hunting!

**Comment by michaelsoriano** [comment]
Awesome @devloco! will update asap. Thanks.
