### ISSUE TITLE
How can we use localization and react-hot-loader here?

### ISSUE THREAD

**Issue by shamimmoeen** [devloco/create-react-wptheme#23]

**Comment by devloco** [comment]
Hi @shamimmoeen,

I prefer i18next  for localization:
https://www.i18next.com/

They do have a React enabled version, but I usually just use the normal, non-React version, even in React apps. But you can check it out here:
https://react.i18next.com/

An interesting alternative is:
https://objectpartners.com/2019/04/03/translate-create-react-app-with-react-intl/
I've looked at that a few times, but have not actually used it.

Then, of course, the big question is, "how do I get the desired translated strings down to the client theme?"

The simplest approach is to jam them into a <script> tag in index.php. Something like:
```
<script>
// note the use of "back ticks" instead of normal quotes
var translationsJson =`<?php $MY_STRINGS_IN_PROPER_JSON_FORMAT ?>`;
var i18Strings = JSON.parse(translationsJson);
</script>
```

And then you can use the `i18Strings` from any where in your React code since it's a global variable.

**Comment by devloco** [comment]
As for `react-hot-loader` ... I haven't looked at it in a long time. But looking at now, it seems they've made a lot of progress.

I'll have to look at it when I have time. The biggest hurdle is that all the instructions are for integrating into WebpackDevServer, which I'm not using at all for this project.

So it'll probably take me some time to get it running. I'll play around with that when I can. Apologies I can't make any promises though.

**Comment by devloco** [comment]
This looks like a decent tutorial for i18Next:

https://dev.to/ksushiva/how-to-translate-your-react-js-app-with-i18next-12mn

**Comment by shamimmoeen** [comment]
> Hi @shamimmoeen,
> 
> I prefer i18next for localization:
> https://www.i18next.com/
> 
> They do have a React enabled version, but I usually just use the normal, non-React version, even in React apps. But you can check it out here:
> https://react.i18next.com/
> 
> An interesting alternative is:
> https://objectpartners.com/2019/04/03/translate-create-react-app-with-react-intl/
> I've looked at that a few times, but have not actually used it.
> 
> Then, of course, the big question is, "how do I get the desired translated strings down to the client theme?"
> 
> The simplest approach is to jam them into a <script> tag in index.php. Something like:
> 
> ```
> <script>
> // note the use of "back ticks" instead of normal quotes
> var translationsJson =`<?php $MY_STRINGS_IN_PROPER_JSON_FORMAT ?>`;
> var i18Strings = JSON.parse(translationsJson);
> </script>
> ```
> 
> And then you can use the `i18Strings` from any where in your React code since it's a global variable.

Can we use the same approach described in here, https://developer.wordpress.org/block-editor/developers/internationalization/

**Comment by devloco** [comment]
I think so... I've never done it that way. But you can put any PHP files you want into the folder: 
`<Your Theme Folder>/react-src/public`

And every time a build happens, those files get copied as part of the build.

Sometimes adding new files while `npm run start` is running causes problems. I suggest restarting it after adding a new file for the first time.
